# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sasha/ClionProjects/Basics

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sasha/ClionProjects/Basics

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sasha/ClionProjects/Basics/CMakeFiles /home/sasha/ClionProjects/Basics/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sasha/ClionProjects/Basics/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Basics

# Build rule for target.
Basics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Basics
.PHONY : Basics

# fast build rule for target.
Basics/fast:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/build
.PHONY : Basics/fast

lab1.o: lab1.cpp.o

.PHONY : lab1.o

# target to build an object file
lab1.cpp.o:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/lab1.cpp.o
.PHONY : lab1.cpp.o

lab1.i: lab1.cpp.i

.PHONY : lab1.i

# target to preprocess a source file
lab1.cpp.i:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/lab1.cpp.i
.PHONY : lab1.cpp.i

lab1.s: lab1.cpp.s

.PHONY : lab1.s

# target to generate assembly for a file
lab1.cpp.s:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/lab1.cpp.s
.PHONY : lab1.cpp.s

lab10.o: lab10.cpp.o

.PHONY : lab10.o

# target to build an object file
lab10.cpp.o:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/lab10.cpp.o
.PHONY : lab10.cpp.o

lab10.i: lab10.cpp.i

.PHONY : lab10.i

# target to preprocess a source file
lab10.cpp.i:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/lab10.cpp.i
.PHONY : lab10.cpp.i

lab10.s: lab10.cpp.s

.PHONY : lab10.s

# target to generate assembly for a file
lab10.cpp.s:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/lab10.cpp.s
.PHONY : lab10.cpp.s

lab2.o: lab2.cpp.o

.PHONY : lab2.o

# target to build an object file
lab2.cpp.o:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/lab2.cpp.o
.PHONY : lab2.cpp.o

lab2.i: lab2.cpp.i

.PHONY : lab2.i

# target to preprocess a source file
lab2.cpp.i:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/lab2.cpp.i
.PHONY : lab2.cpp.i

lab2.s: lab2.cpp.s

.PHONY : lab2.s

# target to generate assembly for a file
lab2.cpp.s:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/lab2.cpp.s
.PHONY : lab2.cpp.s

lab3.o: lab3.cpp.o

.PHONY : lab3.o

# target to build an object file
lab3.cpp.o:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/lab3.cpp.o
.PHONY : lab3.cpp.o

lab3.i: lab3.cpp.i

.PHONY : lab3.i

# target to preprocess a source file
lab3.cpp.i:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/lab3.cpp.i
.PHONY : lab3.cpp.i

lab3.s: lab3.cpp.s

.PHONY : lab3.s

# target to generate assembly for a file
lab3.cpp.s:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/lab3.cpp.s
.PHONY : lab3.cpp.s

lab4.o: lab4.cpp.o

.PHONY : lab4.o

# target to build an object file
lab4.cpp.o:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/lab4.cpp.o
.PHONY : lab4.cpp.o

lab4.i: lab4.cpp.i

.PHONY : lab4.i

# target to preprocess a source file
lab4.cpp.i:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/lab4.cpp.i
.PHONY : lab4.cpp.i

lab4.s: lab4.cpp.s

.PHONY : lab4.s

# target to generate assembly for a file
lab4.cpp.s:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/lab4.cpp.s
.PHONY : lab4.cpp.s

lab6.o: lab6.cpp.o

.PHONY : lab6.o

# target to build an object file
lab6.cpp.o:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/lab6.cpp.o
.PHONY : lab6.cpp.o

lab6.i: lab6.cpp.i

.PHONY : lab6.i

# target to preprocess a source file
lab6.cpp.i:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/lab6.cpp.i
.PHONY : lab6.cpp.i

lab6.s: lab6.cpp.s

.PHONY : lab6.s

# target to generate assembly for a file
lab6.cpp.s:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/lab6.cpp.s
.PHONY : lab6.cpp.s

lab8.o: lab8.cpp.o

.PHONY : lab8.o

# target to build an object file
lab8.cpp.o:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/lab8.cpp.o
.PHONY : lab8.cpp.o

lab8.i: lab8.cpp.i

.PHONY : lab8.i

# target to preprocess a source file
lab8.cpp.i:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/lab8.cpp.i
.PHONY : lab8.cpp.i

lab8.s: lab8.cpp.s

.PHONY : lab8.s

# target to generate assembly for a file
lab8.cpp.s:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/lab8.cpp.s
.PHONY : lab8.cpp.s

lab9.o: lab9.cpp.o

.PHONY : lab9.o

# target to build an object file
lab9.cpp.o:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/lab9.cpp.o
.PHONY : lab9.cpp.o

lab9.i: lab9.cpp.i

.PHONY : lab9.i

# target to preprocess a source file
lab9.cpp.i:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/lab9.cpp.i
.PHONY : lab9.cpp.i

lab9.s: lab9.cpp.s

.PHONY : lab9.s

# target to generate assembly for a file
lab9.cpp.s:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/lab9.cpp.s
.PHONY : lab9.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Basics.dir/build.make CMakeFiles/Basics.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Basics"
	@echo "... lab1.o"
	@echo "... lab1.i"
	@echo "... lab1.s"
	@echo "... lab10.o"
	@echo "... lab10.i"
	@echo "... lab10.s"
	@echo "... lab2.o"
	@echo "... lab2.i"
	@echo "... lab2.s"
	@echo "... lab3.o"
	@echo "... lab3.i"
	@echo "... lab3.s"
	@echo "... lab4.o"
	@echo "... lab4.i"
	@echo "... lab4.s"
	@echo "... lab6.o"
	@echo "... lab6.i"
	@echo "... lab6.s"
	@echo "... lab8.o"
	@echo "... lab8.i"
	@echo "... lab8.s"
	@echo "... lab9.o"
	@echo "... lab9.i"
	@echo "... lab9.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

